### ISSUE TITLE
Multi-Inputs don't get recognized.

### ISSUE THREAD

**Issue by thehamish555** [MelanX/SkyGUIs#11]
### Minecraft version

1.20.1

### Sky GUIs version

1.20.1-3.0.16

### Skyblock Builder version

1.20.1-5.1.23

### LibX version

1.20.1-5.0.12

### Forge version

47.3.10

### The latest.log file

https://gist.github.com/thehamish555/63d72a5a7c5ddd0cb79e2d3e6be0952c

### Issue description

Upon setting the key bind to multi-inputs (E.g. CTRL+L), the mod fails to open the required GUI. 

### Steps to reproduce

1. in options.txt change the mapping to key_skyguis.key.all_teams_screen:key.keyboard.l:CONTROL (or use external mods)
2. Launch the game
3. Play a world, and attempt to open the GUI

Bonus: Change keybind back to L or another single input and check that it still works normally.

### Other information

Some people have stated they do not have this issue, where some do. All configs are the same across the devices that work and don't.

**Comment by MelanX** [comment]
I'm sorry, but I cannot reproduce it. I think I did all the required things.

https://github.com/user-attachments/assets/9de725eb-8ea1-4772-a7c3-7ded5131422a

**Comment by thehamish555** [comment]
It's possible that the issue maybe related to Windows? If you are able to test this on windows that would be great. I unfortunately probably can't tell you what version of windows it was since I have updated since then.

**Comment by MelanX** [comment]
On Windows 11, I get the same result. No matter which control button I use. 
![image](https://github.com/user-attachments/assets/607149a7-42b1-46b1-aceb-0d1a0154a404)
