### ISSUE TITLE
[Feature Request]: Add description text for template

### ISSUE THREAD

**Issue by Affehund** [MelanX/SkyGUIs#3]
### Describe your idea

In the create team gui it would be useful to see the description of the selected team anywhere. 
Maybe either with a text below the template button or a hover text?

**Comment by MelanX** [comment]
Fixed it, didn’t remember that issue :)

https://github.com/MelanX/SkyGUIs/commit/c925d20cf9f52351c123febc6335e4dbe31a8ac0
