### ISSUE TITLE
Not Bound key for Sky GUIs conflict with volume control

### ISSUE THREAD

**Issue by Hamredahl** [MelanX/SkyGUIs#7]
### Minecraft version

1.20.1

### Sky GUIs version

1.20.1-3.0.11

### Skyblock Builder version

1.20.1-5.1.16

### LibX version

1.20.1-5.0.12

### Forge version

47.2.20

### The latest.log file

N/A

### Issue description

If "Open main screen" is not bound to any key, it seems to conflict with any kind of volume control. Attempting to adjust volume will then also open the Sky GUIs main screen. 

### Steps to reproduce

1. Go to options, controls, key binds
2. Remove key bind from "Open main screen" in category Sky GUIs
3. Exit menu and return to game
4. Attempt to adjust volume with peripheral volume control. 

### Other information

This behavior has been seen from both keyboard and headset volume control on the same computer (both brand Logitech), and on a separate computer (brand of peripheral unknown). It has also been seen in multiple modpacks (All the Mods 9 - To the Sky and Seaopolis Submerged), and a custom modpack with only Sky GUIs and dependencies added.

**Comment by MelanX** [comment]
That's really funny. Thanks :D

**Comment by Hamredahl** [comment]
I had a very incredulous but good laugh when I discovered it I'll admit. Happy to help!
